apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-streams-scaling-jmx-configmap
data:
  # Streams MBean server via localhost because they run within the same Pod
  jmx-prometheus.yml: |+
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
      - pattern: ".*"

